{
 "title": "FastAPI Dashboard",
 "refresh": "5s",
 "panels": [
  {
   "title": "Llamadas a /",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "main_requests_total" }
   ]
  },
  {
   "title": "Llamadas a /health",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "healthcheck_requests_total" }
   ]
  },
  {
   "title": "Llamadas a /bye",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 4 },
   "targets": [
    { "expr": "bye_requests_total" }
   ]
  },
  {
   "title": "Reinicios de la App",
   "type": "stat",
   "gridPos": { "x": 6, "y": 4, "w": 6, "h": 4 },
   "targets": [
    { "expr": "fastapi_app_starts_total" }
   ]
  },
  {
   "title": "Uso actual de CPU (real)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 8, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"fastapi.*\"}[2m]))"
    }
   ]
  },
  {
   "title": "CPU Request asignado",
   "type": "stat",
   "gridPos": { "x": 6, "y": 8, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum by(pod) (kube_pod_container_resource_requests_cpu_cores{namespace=\"default\", pod=~\"fastapi.*\"})"
    }
   ]
  },
  {
   "title": "Alertas Activas",
   "type": "table",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\"}"
    }
   ]
  },
  {
   "title": "Reinicios del contenedor",
   "type": "stat",
   "gridPos": { "x": 0, "y": 18, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{namespace=\"default\"}[5m])"
    }
   ]
  },
  {
   "title": "Total de peticiones",
   "type": "stat",
   "gridPos": { "x": 6, "y": 18, "w": 6, "h": 4 },
   "targets": [
    { "expr": "server_requests_total" }
   ]
  }
 ]
}